[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node --loader ts-node/esm src/index.ts"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
